version: '3.8'

services:
  app:
    extends:
      file: ./docker/docker-compose.yml
      service: app
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  db:
    extends:
      file: ./docker/docker-compose.yml
      service: db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 