#!/usr/bin/env node

import { execSync } from 'child_process';

try {
  console.log('Running dependency verification...');
  execSync('npm run verify-deps', { stdio: 'inherit' });
} catch (error) {
  console.error('Dependency verification failed');
  process.exit(1);
}
