#!/usr/bin/env node
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

try {
  execSync('npm run verify-deps', { stdio: 'inherit' });
} catch (error) {
  process.exit(1);
}
